mod application;
pub mod configuration;
pub mod controller;
pub mod extensions;
pub mod hosted_service;
pub mod http_context;
pub mod http_listener;
pub mod io;
pub mod logging;
pub mod middleware;
pub mod services;
pub mod tcp;
pub mod threading;
pub mod utils;

pub use application::{Application, ApplicationBuilder};
pub use asp_dot_rust_macros::controller_route;
// pub use controller::{delete, get, head, options, patch, post, put, route};
pub use inventory;
pub type MutexAsync<T> = tokio::sync::Mutex<T>;
